image: node:latest

stages:
  - test
  - production

test:
  stage: test
  script:
    - npm install
    - npm test

production:
  type: deploy
  stage: production
  image: node:10
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - npm install
    - dpl --provider=heroku --app=app-vuttr-cw --api-key=$HEROKU_API_KEY
  only:
    - master
